name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        framework: ['v2.0', 'v3.5', 'v4.0', 'v4.5', 'v4.6.1', 'v4.7.2', 'v4.8']
        platform: ['Any CPU']
        configuration: ['Release']

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build Solution
      run: |
        msbuild SeBackupPrivilege.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="${{ matrix.platform }}" /p:TargetFrameworkVersion=${{ matrix.framework }} /p:OutputPath=bin\${{ matrix.configuration }}\AnyCPU\${{ matrix.framework }}\ /p:UseRoslynCompiler=false

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-AnyCPU-${{ matrix.framework }}
        path: |
          SeBackupPrivilegeUtils/bin/${{ matrix.configuration }}/AnyCPU/${{ matrix.framework }}/
          SeBackupPrivilegeCmdLets/bin/${{ matrix.configuration }}/AnyCPU/${{ matrix.framework }}/
          SeBackupPrivilegeTest/bin/${{ matrix.configuration }}/AnyCPU/${{ matrix.framework }}/ 